# -*- coding: utf-8 -*-
"""automate_Cecilia Agnes Vechrisda Manalu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLaQaEOB8g4q50C5sXKUGIBVnKgJ_6d1
"""

import os
import shutil
import zipfile
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def preprocess(input_path, output_dir):
    df = pd.read_csv(input_path)
    df = df[df['TotalCharges'].astype(str).str.strip() != '']
    df['TotalCharges'] = df['TotalCharges'].astype(float)
    df = df.drop_duplicates()
    df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

    cat_cols = df.select_dtypes(include='object').columns.tolist()
    if 'customerID' in cat_cols:
        cat_cols.remove('customerID')
    df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)

    num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
    scaler = StandardScaler()
    df_encoded[num_cols] = scaler.fit_transform(df_encoded[num_cols])

    X = df_encoded.drop(['customerID', 'Churn'], axis=1)
    y = df_encoded['Churn']
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    os.makedirs(output_dir, exist_ok=True)
    pd.concat([X_train, y_train], axis=1).to_csv(os.path.join(output_dir, 'train.csv'), index=False)
    pd.concat([X_test, y_test], axis=1).to_csv(os.path.join(output_dir, 'test.csv'), index=False)

if __name__ == "__main__":
    preprocess('WA_Fn-UseC_-Telco-Customer-Churn.csv', 'namadataset_preprocessing')

# Nama folder yang ingin didownload
folder_name = 'namadataset_preprocessing'
zip_name = f'{folder_name}.zip'

# Hapus file zip lama jika ada
if os.path.exists(zip_name):
    os.remove(zip_name)

# Kompres folder menjadi zip
shutil.make_archive(folder_name, 'zip', folder_name)